### ISSUE TITLE
Error in update step

### ISSUE THREAD

**Issue by pfeuffer** [scm-manager/scm-notify-plugin#3]
## Issue description

The update step from 1.x seems to have an issue when not all properties had been set in 1.x for the notify plugin.

### Bug Report

See scm-manager/scm-manager#1235 for the details.

Relevant log excerpt:

```
java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:662)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at sonia.scm.notify.update.NotifyV2RepositoryConfigMigrationUpdateStep.buildConfig(NotifyV2RepositoryConfigMigrationUpdateStep.java:89)
at sonia.scm.notify.update.NotifyV2RepositoryConfigMigrationUpdateStep.lambda$doUpdate$0(NotifyV2RepositoryConfigMigrationUpdateStep.java:73)
```

**Comment by pfeuffer** [comment]
Fixes scm-manager/scm-manager#1235
